name: GHCR Container Retention
permissions:
  contents: read
  packages: write
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  delete-package-versions:
    name: Delete untagged package versions
    runs-on: ubuntu-latest
    steps:
      - uses: snok/container-retention-policy@v3.1.0
        with:
          account: user
          token: ${{ secrets.GHCR_X }}
          image-names: "*"
          image-tags: "!latest"
          tag-selection: both
          cut-off: 1h
